CREATE DATABASE IF NOT EXISTS smartmei;

use smartmei;

CREATE TABLE IF NOT EXISTS users (
    id       varchar(40) NOT NULL PRIMARY KEY,
    name     VARCHAR(120) NOT NULL ,
    email    VARCHAR(255) DEFAULT NULL,
    status   VARCHAR(8)   DEFAULT NULL,
    birthday DATE NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS books (
    id       varchar(80) NOT NULL PRIMARY KEY,
    title    VARCHAR(120) NOT NULL ,
    user_id  VARCHAR(100) DEFAULT NULL,
    pages   VARCHAR(8)   DEFAULT NULL,
    status   VARCHAR(8)   DEFAULT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;